OPENAI_API_KEY = "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"
assistant_id_a1_20 = "asst_jpp6vcDAXPKqmvpVKStAG49Q"
assistant_id_a1_200 = "asst_oD8fP9bP1DiBEMlNM0ss7pDE"
assistant_id_a2_20 = "asst_R8rJeDVJr7PiXMpIi29yJ5hh"
assistant_id_a2_200 = "asst_weZpLpFrGiMT45kUq952CXu0"
assistant_id_b1_20 = "asst_zpyZqJ6ZoVStxfQO7t324rAZ"
assistant_id_b1_200 = "asst_RnUdBN0fRREIq7LKPH10ltnI"
assistant_id_b2_20 = "asst_Zm22hm6d8ZdOxTrinyPmaqGZ"
assistant_id_b2_200 = "asst_3qlLOhsbVQtoNpRSp5zW5EDx"



assistant_id_a1_20_copy = "asst_JQwally3vL9Lf9rIv5zQAQI4"
assistant_id_a1_200_copy = "asst_skYktKOhEuiTuE0qr63EjBiZ"
assistant_id_a2_20_copy = "asst_a2ZUbcg9HZ4qVHy91QRGWSLp"
assistant_id_a2_200_copy = "asst_GnlbdJ4ndDl1Ky2L24tpQX15"
assistant_id_b1_20_copy = "asst_iZUxnEpEkHdlcypJcisJfNEC"
assistant_id_b1_200_copy = "asst_MZHmMmNxTJyq2BSr9ICemMPN"
assistant_id_b2_20_copy = "asst_NqkEOEdwk0TKF4X2rgRkVWlN"
assistant_id_b2_200_copy = "asst_6D2BUAGJffBBGtAiB5XzGCFb"


